-- ============================================
-- Reverse of 059_vulnerabilities_epss_checked_at.up.sql (M46 Codex final
-- round, Low #2).
--
-- Drops epss_checked_at and restores migration 055's original COMMENT text
-- on epss_updated_at verbatim, reverting vulnerabilities to its post-055
-- shape. Fully round-trippable: epss_checked_at carries only a derived
-- freshness timestamp (no backfill, no state any other column depends on),
-- so dropping it loses nothing that the next epss_sync cannot re-establish.
-- The COMMENT ON COLUMN annotation is dropped together with its column.
--
-- ROLLBACK SEQUENCING -- read before running this down:
--   This migration is NOT safe to apply under an application build that
--   expects 059. Three statements in repository/vulnerability.go name
--   epss_checked_at directly -- UpdateEPSSScores writes it, and GetByID /
--   GetByCVE both SELECT it -- so once the column is dropped, every EPSS
--   sync write and every single-vulnerability read fails with
--   `column "epss_checked_at" does not exist` (i.e. 500s on the
--   vulnerability detail path, not merely a lost freshness signal). Roll the
--   API binary back to a pre-059 build FIRST, then run this down. The
--   reverse order (down first) takes the detail endpoints out of service
--   until the binary follows.
--
--   SEMANTIC ROLLBACK -- this down is NOT purely structural (M46 Codex final
--   round, Low #3). An earlier draft of this note claimed the writer's OTHER
--   059 behaviour (epss_updated_at moving only when a score is actually
--   written) "needs no rollback: it is exactly what 055 already specified".
--   That is true of the 055 CONTRACT but false of the pre-059 BINARY this
--   file instructs you to roll back to. The parent commit's
--   UpdateEPSSScores is def6a46's:
--
--       SET epss_score = $1, epss_percentile = $2, epss_updated_at = NOW()
--
--   -- an unconditional NOW(), so it stamps epss_updated_at on TOMBSTONE
--   writes too (score cleared to NULL). Running this down therefore restores
--   055's COMMENT and then immediately hands the column to a writer that
--   breaks it again: the first post-rollback epss_sync that clears any CVE
--   reintroduces "fresh epss_updated_at beside a NULL epss_score", the exact
--   misleading state 059 existed to remove, and it is published straight
--   through the JSON API as `epss_updated_at`.
--
--   Nothing here can prevent that -- it is a property of the older binary --
--   so treat it as an accepted cost of the rollback, not as an oversight.
--   Rows so written are reconciled the next time a sync ANSWERS for that CVE
--   after 059 is re-applied -- not merely the next sync run. A CVE that FIRST
--   does not cover is only touched by MarkEPSSChecked, which moves
--   epss_checked_at and nothing else, so a stale epss_updated_at beside a
--   NULL epss_score can persist indefinitely on such a row. 059 does no
--   backfill in either direction. If the rollback is expected to last,
--   disable the epss_sync scheduler job while it does.
--
-- RLS is untouched (vulnerabilities is a global, non-tenant structural
-- exemption; 059 declared no RLS).
-- ============================================

ALTER TABLE vulnerabilities DROP COLUMN IF EXISTS epss_checked_at;

COMMENT ON COLUMN vulnerabilities.epss_updated_at IS
    'M36-A / F432 (#154): timestamp of the last successful EPSS sync for this CVE (TIMESTAMPTZ). Global non-tenant attribute. NULL until the scheduled epss_sync (M36-B) writes a score. Promoted verbatim from orphan packages/db 006_epss.sql.';
