-- ============================================
-- Drop vulnerabilities.tenant_id — a dead column whose only effect was to
-- make the shared CVE catalogue LOOK tenant-scoped (M48 follow-up).
--
-- What this removes:
--   Migration 007 added `tenant_id UUID REFERENCES tenants(id) ON DELETE SET
--   NULL` to `vulnerabilities` in the same sweep that promoted projects /
--   sboms / components / vex_statements / api_keys, and gave it the matching
--   `idx_vulnerabilities_tenant_id`. Unlike every other table in that list,
--   `vulnerabilities` never got RLS — 007's own trailing comment says so
--   ("vulnerabilities table doesn't have RLS as vulnerabilities are shared
--   across tenants"), and the lint-migration-rls tool records the table as a
--   structural exemption for exactly that reason.
--
--   So the column was a tenant_id on a table that is deliberately NOT
--   tenant-scoped. It has never been an isolation boundary and nothing has
--   ever behaved as if it were.
--
-- Why it is safe to drop — the column has no reader and no product writer:
--   * No SELECT, WHERE, JOIN or ORDER BY in any DEPLOYED code path references
--     it. `vulnerabilities` is most often aliased `v`, and `v.tenant_id`
--     occurs in no deployed query (the `v.tenant_id` hits in migration 045
--     bind `v` to vex_statements, a different table). No alias count is
--     quoted here on purpose: round 1 carried a "43 places" figure that does
--     not reproduce under any defensible scope (44 textual / 42 excluding
--     comments), and a brittle number invites the next reader to trust it
--     rather than re-run the search (Codex round 2, #5).
--     The one exception is deliberate and is not a deployed reader: this
--     change's own regression test issues `SELECT COUNT(tenant_id) FROM
--     vulnerabilities` as a negative control, and only after
--     information_schema has proved the column came back (Codex round 1, #5 —
--     the original wording here said "anywhere in apps/api/internal/**", which
--     that test contradicts).
--   * There is no `SELECT * FROM vulnerabilities` anywhere, so no query pulls
--     the column in implicitly.
--   * model.Vulnerability (Go) has no TenantID field and the TypeScript
--     `Vulnerability` interface in apps/web/src/lib/api.ts has no tenant_id —
--     the column has never crossed the API boundary in either direction.
--   * VulnerabilityRepository.Create (the upsert — INSERT … ON CONFLICT DO
--     UPDATE; there is no method named Upsert, Codex round 2 #6) has the
--     INSERT column list (id, cve_id, description, severity, cvss_score,
--     source, published_at, updated_at) and the CVE-sync scheduler's insert is
--     the same shape: neither names tenant_id, so every row the product
--     creates leaves it NULL. No UPDATE statement in the tree sets it.
--   * The only writers in the repository were two E2E fixtures —
--     docker/seed/web-e2e.sql (4 rows, tenant …0001) and
--     scripts/golden-path-e2e.sh (1 row, explicit NULL). Both are updated in
--     the same change as this migration to stop naming the column; neither
--     ever read it back.
--   * packages/mcp-server has zero tenant_id references of any kind.
--
--   Measured on the 2026-07-30 dev DB before writing this: 10,899 rows,
--   0 of them with a non-NULL tenant_id. That is a statement about the dev DB
--   only — see "Existing data" below for what a production instance may hold.
--
-- DB-side dependencies, enumerated (pg_depend on the column's attnum):
--   Exactly two objects depend on this column, and both are owned BY it:
--     * vulnerabilities_tenant_id_fkey — the column's own FK to tenants(id).
--     * idx_vulnerabilities_tenant_id  — the column's own btree index.
--   No view, no materialised view, no rule, no trigger, no RLS policy (the
--   table has none, and no policy on any OTHER table mentions
--   `vulnerabilities` in its USING / WITH CHECK expression), and no stored
--   function body references the table. Every inbound FK from
--   component_vulnerabilities / vex_statements / vulnerability_tickets /
--   vulnerability_resolution_events / ssvc_assessments targets
--   `vulnerabilities(id)`, never tenant_id.
--
--   DROP COLUMN would remove both dependents implicitly; the index is dropped
--   explicitly first so the change reads as deliberate (the 062 precedent).
--
-- Why DROP rather than leave it NULL forever:
--   A `tenant_id` column is the single strongest signal in this schema that a
--   table is tenant-scoped, and this codebase has already shipped
--   cross-tenant bugs founded on exactly that inference. Migration 062 is the
--   nearest example: `ssvc_decision` was stamped onto these same shared rows
--   because the row looked tenant-owned. A dormant tenant_id invites the next
--   author to write `WHERE tenant_id = $1` here and believe they are scoped —
--   which would silently return one tenant's rows to nobody and hide the
--   whole global catalogue, or worse, to write a tenant's data onto a shared
--   row. There is no RLS backstop on this table by design, so nothing would
--   catch it. Removing the column makes that mistake impossible to make
--   silently: the query fails to compile at the database.
--
--   `vulnerabilities` remains a structural exemption in lint-migration-rls
--   after this migration — the detector still sees 007's `ALTER TABLE
--   vulnerabilities ADD COLUMN tenant_id` (that file is not modified) and the
--   exemption keeps it from being flagged. The exemption is now a statement
--   about a historical DDL line rather than about a live column.
--
-- Existing data:
--   The values are discarded. Their provenance is UNSUPPORTED — we cannot say
--   what a non-NULL value meant, and that is precisely the point (Codex round
--   2, #7: round 1 asserted it recorded "the tenant that created the CVE row
--   first", which contradicts this file's own writer analysis).
--
--   What IS established: no product path IN THIS TREE OR ITS REACHABLE GIT
--   HISTORY supplies or reads the column (`git log --all -G 'INSERT INTO
--   vulnerabilities[^;]*tenant_id'` finds only the two E2E fixtures named
--   above). What is NOT established, and cannot be: what every historical
--   deployed build did. The scope qualifier matters — round 2 wrote "ever",
--   which the search cannot support and which contradicts the very
--   possibility this paragraph goes on to allow (Codex round 3, #4).
--
--   So a non-NULL value on some other instance could have come from operator
--   SQL or a path not present here; nothing else in the schema recorded it,
--   so it cannot be reconstructed or attributed, and after the drop the
--   database cannot identify its writer either. No reader in this tree
--   consumed it, so nothing here depended on whatever it held. On the dev DB
--   this drop is a no-op (0 non-NULL rows measured 2026-07-30); an instance
--   seeded through docker/seed/web-e2e.sql will have a handful of rows
--   carrying the fixture tenant id.
--
-- RLS:
--   `vulnerabilities` has relrowsecurity = false, relforcerowsecurity = false
--   and zero policies (verified on the dev DB). Dropping a column touches
--   neither, exactly as 007 added it without any RLS statements for this
--   table. The lint-migration-rls gate is a no-op for this migration: it
--   scans `*.up.sql` only, and this file declares no tenant_id column and
--   ALTER-promotes nothing.
--
-- Migrator role:
--   Runs as sbomhub_migrator (MIGRATE_DATABASE_URL), the table owner. No
--   grants change; the runtime role sbomhub_app keeps its existing
--   table-level privileges, which are not column-scoped for this table.
--
-- DEPLOY SEQUENCING — read before applying this up:
--   Safe in either order for the API binary. No API build, past or present,
--   reads or writes this column, so an old instance running against the
--   post-063 schema behaves identically to one running against the pre-063
--   schema. This is not the 062 situation, where a stale writer would have
--   500'd; there is no writer to drain.
--
--   The two things that DO break on the post-063 schema are the E2E fixtures
--   that name the column in their INSERT lists. Both are updated in the same
--   commit, so a checkout that has this migration also has the fixed
--   fixtures. A CI run that applies 063 while replaying an OLDER checkout of
--   docker/seed/web-e2e.sql or scripts/golden-path-e2e.sh will fail with
--   `column "tenant_id" of relation "vulnerabilities" does not exist`.
-- ============================================

-- LOCK BUDGET (Codex round 1, Medium):
--   Both statements below need ACCESS EXCLUSIVE on `vulnerabilities`. The work
--   itself is metadata-only and finishes in milliseconds regardless of row
--   count — the risk is not the drop, it is WAITING for the lock. The migrator
--   role runs with lock_timeout = 0, so on a live instance a single
--   long-running reader holding ACCESS SHARE would make this migration block
--   indefinitely, and (because it also queues ahead of subsequent lock
--   requests) stall every other query against the table behind it.
--
--   A bounded timeout turns that from an outage into a retry: the runner wraps
--   each migration file in one transaction (cmd/migrate/main.go — DDL and the
--   schema_migrations row commit together), so a timeout rolls back the DDL
--   AND the version record, leaving the database exactly as it was. Re-run
--   `migrate up` when the table is quiet.
--
--   NOTE: 063 is the FIRST migration in this directory to set a lock budget;
--   the other 62 all inherit lock_timeout = 0. That repo-wide gap is a real
--   residual, not something this migration fixes.
SET LOCAL lock_timeout = '5s';

DROP INDEX IF EXISTS idx_vulnerabilities_tenant_id;

ALTER TABLE vulnerabilities DROP COLUMN IF EXISTS tenant_id;
