-- ============================================
-- Reverse of 063_drop_vulnerabilities_tenant_id.up.sql (M48 follow-up).
--
-- Restores the COLUMN AND INDEX exactly as migration 007 declared them: a
-- nullable `tenant_id UUID REFERENCES tenants(id) ON DELETE SET NULL` plus
-- the plain btree `idx_vulnerabilities_tenant_id`. The FK is re-created as a
-- side effect of the column definition, so the restored schema is
-- structurally identical to the pre-063 state (constraint name included:
-- Postgres derives `vulnerabilities_tenant_id_fkey` from table + column +
-- suffix, the same name 007 got).
--
-- DATA IS NOT RESTORED, and cannot be. 063 discards the column's contents;
-- nothing else in the schema recorded them, so after this down every row has
-- tenant_id NULL. That loss is intentional. What the values MEANT is
-- unsupported: no product INSERT in this tree or its reachable git history
-- supplies the column, so the only writers we can name are E2E fixtures, and
-- any other non-NULL value could only have come from operator SQL or a
-- historical path not present here (Codex round 2 #7 — the earlier wording
-- claimed they recorded the tenant that created the row first, which the
-- writer analysis contradicts; round 3 #4 — and "ever" overreached what the
-- search can establish, so the claim is scoped to this tree and its reachable
-- history). No reader in this tree consumed the column, so nothing here
-- depended on whatever it held, and there is no correct value to reconstruct
-- for a row shared by every tenant — which is the finding 063 fixes.
--
-- What this down does NOT restore is the property that made the column
-- dangerous: it comes back as a column that still has no reader, no writer,
-- no RLS policy and no isolation meaning on a table that is a structural
-- exemption in lint-migration-rls. Rolling back re-arms the misreading trap
-- (a future `WHERE tenant_id = $1` on the global CVE catalogue that silently
-- matches nothing, with no RLS backstop to catch it) without buying back any
-- behaviour. Prefer rolling forward.
--
-- ROLLBACK SEQUENCING — read before running this down:
--   Order does not matter relative to the API binary. No API build reads or
--   writes vulnerabilities.tenant_id, in either direction, so no deployed
--   binary can tell whether the column is present. This is unlike 062, whose
--   down had to run BEFORE the API rollback because a pre-062 binary required
--   the column.
--
--   The E2E fixtures are the only consumers that care, and they only care in
--   one direction: docker/seed/web-e2e.sql and scripts/golden-path-e2e.sh as
--   of M48 no longer name the column, and they replay correctly against BOTH
--   the pre-063 and post-063 schema (the column is nullable and has no
--   default beyond NULL). A pre-M48 checkout of those fixtures requires the
--   column, so this down is what makes replaying one of them possible again.
-- ============================================

-- LOCK BUDGET (Codex round 2, Medium): the two statements below do NOT have
-- the same lock profile, and round 2's wording that they did was wrong
-- (corrected in round 3, #2 — measured via pg_locks):
--
--   * `ALTER TABLE ... ADD COLUMN ... REFERENCES` takes ACCESS EXCLUSIVE on
--     `vulnerabilities`. It conflicts with READERS, so a live SELECT holding
--     ACCESS SHARE blocks it — and every request queued behind it.
--   * non-CONCURRENT `CREATE INDEX` takes SHARE, which is COMPATIBLE with a
--     reader's ACCESS SHARE (both were observed granted simultaneously). It
--     conflicts with WRITERS (ROW EXCLUSIVE), so it waits behind INSERT /
--     UPDATE / DELETE on the table instead.
--
-- Either way the wait is unbounded without a budget: round 2 held ACCESS SHARE
-- for 8s, ran the real `migrate down 1`, and observed it block until the
-- holder committed with no timeout; round 3 re-ran it with this budget in
-- place and measured failure at 5.034s with `canceling statement due to lock
-- timeout`, after which a catalog fingerprint (24 objects: columns, defaults,
-- indexes, constraints, RLS flags) was byte-identical to the pre-run state and
-- the 063 schema_migrations row still carried its original timestamp.
--
-- The runner wraps a down migration in one transaction, which is what makes
-- that clean rollback possible.
SET LOCAL lock_timeout = '5s';

ALTER TABLE vulnerabilities
    ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_vulnerabilities_tenant_id ON vulnerabilities(tenant_id);
