-- ============================================
-- Add (but do not yet verify) a CHECK constraining components.eol_status to
-- the four statuses the product defines. Migration 065 verifies it.
--
-- What this closes:
--   `eol_status` is a nullable varchar with DDL default 'unknown' and, until
--   now, no constraint. The only writer is
--   EOLRepository.UpdateComponentEOLStatus, which bound the caller's
--   model.EOLStatus straight into the UPDATE. That type is a string type, so
--   its zero value is "" — and "" is not just "some other string", it is the
--   value that COLLIDES with SQL NULL on read: model.Component types
--   EOLStatus as a plain string, so GetComponentsWithEOL maps both NULL and ''
--   to "". A row written with '' becomes indistinguishable from a row that was
--   never assessed.
--
--   No current-tree production caller supplies another value (the single
--   caller initialises Status to 'unknown' and only ever reassigns 'active',
--   'eol' or 'eos'), and the measured dev DB contains none. That is the whole
--   of the evidence: it says nothing about historical deployed builds or about
--   operator SQL, so it is a reason to constrain the column, not a reason to
--   consider it already safe.
--
-- Belt and braces, matching how this repository treats authorisation input:
--   belt   — repository/eol.go validates against validEOLStatuses and returns
--            ErrInvalidEOLStatus before issuing the UPDATE. This is the half
--            that produces a message naming the field.
--   braces — this CHECK. It also covers writers that bypass the repository
--            (operator SQL, a future second writer, a migration).
--
--   The two lists must stay in step. Adding a status to the Go allowlist
--   without amending this constraint moves the failure from a clear
--   application error to a constraint violation at write time.
--
-- NULL is still allowed:
--   The column is nullable and rows may hold NULL. This migration excludes
--   meaningless values; it does not make the column mandatory.
--   `eol_status IS NULL` short-circuits the IN test.
--
-- WHY THIS IS SPLIT ACROSS 064 AND 065 — and why the split has to be across
-- MIGRATION FILES rather than across statements:
--   A plain `ADD CONSTRAINT ... CHECK` verifies every existing row while
--   holding ACCESS EXCLUSIVE, blocking all readers and writers of `components`
--   for the scan. Splitting into NOT VALID + VALIDATE is the standard remedy,
--   because VALIDATE takes only SHARE UPDATE EXCLUSIVE, which does not
--   conflict with reads or ordinary writes.
--
--   That remedy only works if the two statements are in SEPARATE
--   TRANSACTIONS. PostgreSQL holds a lock until the transaction ends, and
--   cmd/migrate/main.go wraps each migration FILE in one transaction — so
--   putting both statements in one file keeps the ACCESS EXCLUSIVE lock from
--   the first statement held across the validation scan and achieves nothing.
--
--   Measured on PostgreSQL 15.18 (Codex round 1, Medium #1 — the first version
--   of this migration made exactly that mistake while citing 063's lock
--   lesson): with both statements in one transaction, pg_locks showed
--   AccessExclusiveLock still held during VALIDATE and a concurrent
--   `SET lock_timeout='750ms'; SELECT count(*) FROM components` timed out.
--   With the ADD committed first and VALIDATE run in a new transaction,
--   pg_locks showed only ShareUpdateExclusiveLock and the concurrent read
--   succeeded.
--
--   So: this file adds the constraint and COMMITS; 065 validates it in its own
--   transaction. "Brief" here means SCAN-FREE, not short-lived: the ADD itself
--   is catalogue-only, but the ACCESS EXCLUSIVE lock is held until this
--   transaction commits — which includes the runner's INSERT into
--   schema_migrations (Codex round 2 #4 held that table in SHARE mode and
--   observed the lock still granted on `components` while the runner blocked).
--   The window is bounded by the runner's own work, not by the DDL alone.
--
--   Between 064 and 065 the constraint is enforced for NEW rows and not yet
--   proven for old ones — the correct intermediate state, not a gap: bad
--   writes are already refused.
--
-- LOCK BUDGET: see 063. This ADD does no table scan, but as above the lock it
--   takes lives until COMMIT, and acquiring it can queue behind a live reader.
--   A bounded wait turns an indefinite stall into a retry; the runner's
--   transaction rolls back the DDL and the schema_migrations row together.
--   lock_timeout bounds ACQUISITION of each statement's locks, not how long
--   they are then held.
-- ============================================

SET LOCAL lock_timeout = '5s';

ALTER TABLE components
    ADD CONSTRAINT components_eol_status_check
    CHECK (eol_status IS NULL OR eol_status IN ('unknown', 'active', 'eol', 'eos'))
    NOT VALID;
