package middleware

import (
	"log/slog"
	"net/http"
	"strings"

	"github.com/labstack/echo/v4"
	"github.com/sbomhub/sbomhub/internal/config"
	"github.com/sbomhub/sbomhub/internal/repository"
	"github.com/sbomhub/sbomhub/internal/service"
)

// apiKeyPrefix is the literal prefix used for tenant-/project-scoped API keys
// generated by APIKeyService.generateAPIKey (see internal/service/apikey.go:
// `return "sbh_" + hex.EncodeToString(bytes)[:32]`). The MultiAuth middleware
// uses this prefix to decide whether an `Authorization: Bearer ...` value
// should be validated against the API-key table or treated as a Clerk JWT.
const apiKeyPrefix = "sbh_"

// MultiAuth returns a middleware that accepts both Clerk session JWTs (used by
// the Next.js web UI) and API keys (used by the CLI / GitHub Actions). The
// middleware is the single source of truth for the canonical SBOM upload
// endpoint POST /api/v1/projects/:id/sbom — see Trust Rescue 9.3.1 (#9). The
// existing Auth() and APIKeyAuth() middlewares are intentionally left
// untouched so any route that needs strictly one auth model keeps working.
//
// Decision rule:
//   - Authorization: Bearer sbh_... → API key path (apiKeyService.ValidateKey +
//     tenant context derived from the key's own tenant_id).
//   - Any other Bearer value → Clerk JWT path (delegates to Auth()).
//   - Self-hosted mode (no Clerk secret) with no Authorization header → falls
//     through to Auth()'s self-hosted handler, which provisions the default
//     tenant/user. This preserves the "self-host first" promise: a local
//     curl with no header still works against the local server.
//
// Failure modes:
//   - Bearer sbh_<key> that doesn't validate → 401 (does NOT fall through to
//     Clerk; an obviously-shaped API key that fails validation is a hard
//     denial so a leaked-and-revoked key cannot be retried as a JWT).
//   - Empty Authorization in SaaS mode → delegated to Auth(), which returns
//     401 with its usual error body.
func MultiAuth(
	cfg *config.Config,
	tenantRepo *repository.TenantRepository,
	userRepo *repository.UserRepository,
	apiKeyService *service.APIKeyService,
) echo.MiddlewareFunc {
	clerkAuth := Auth(cfg, tenantRepo, userRepo)

	return func(next echo.HandlerFunc) echo.HandlerFunc {
		clerkChain := clerkAuth(next)

		return func(c echo.Context) error {
			authHeader := c.Request().Header.Get("Authorization")
			token := strings.TrimPrefix(authHeader, BearerPrefix)

			// Detect API key by literal prefix. We only treat values with
			// `sbh_` as API keys — anything else (Clerk JWTs, empty, garbage)
			// goes through the Clerk/Self-hosted path.
			if token != authHeader && strings.HasPrefix(token, apiKeyPrefix) {
				return handleAPIKeyAuth(c, token, tenantRepo, apiKeyService, next)
			}

			// Fall back to Clerk JWT (or self-hosted default) path.
			return clerkChain(c)
		}
	}
}

// handleAPIKeyAuth mirrors the APIKeyAuth + APIKeyTenant pair as a single
// inline step so MultiAuth can swap between auth strategies without re-entering
// Echo's middleware chain. Keep the order in sync with apikey.go (validate →
// set ContextKeyAPI → SetCurrentTenant → ContextKeyTenantID).
func handleAPIKeyAuth(
	c echo.Context,
	rawKey string,
	tenantRepo *repository.TenantRepository,
	apiKeyService *service.APIKeyService,
	next echo.HandlerFunc,
) error {
	ctx := c.Request().Context()

	key, err := apiKeyService.ValidateKey(ctx, rawKey)
	if err != nil {
		slog.Debug("MultiAuth: API key validation failed", "error", err)
		return c.JSON(http.StatusUnauthorized, map[string]string{
			"error": err.Error(),
		})
	}
	c.Set(ContextKeyAPI, key)

	// API keys are tenant-scoped — every key carries a tenant_id by schema,
	// which is what enforces tenant isolation through Postgres RLS.
	if err := tenantRepo.SetCurrentTenant(ctx, key.TenantID); err != nil {
		slog.Error("MultiAuth: failed to set tenant context", "error", err)
		return c.JSON(http.StatusInternalServerError, map[string]string{
			"error": "failed to set tenant context",
		})
	}
	c.Set(ContextKeyTenantID, key.TenantID)

	return next(c)
}
