package middleware

import (
	"log/slog"
	"net/http"
	"strings"

	"github.com/labstack/echo/v4"
	"github.com/sbomhub/sbomhub/internal/config"
	"github.com/sbomhub/sbomhub/internal/model"
	"github.com/sbomhub/sbomhub/internal/repository"
	"github.com/sbomhub/sbomhub/internal/service"
)

// apiKeyPrefix is the literal prefix used for tenant-/project-scoped API keys
// generated by APIKeyService.generateAPIKey (see internal/service/apikey.go:
// `return "sbh_" + hex.EncodeToString(bytes)[:32]`). The MultiAuth middleware
// uses this prefix to decide whether an `Authorization: Bearer ...` value
// should be validated against the API-key table or treated as a Clerk JWT.
const apiKeyPrefix = "sbh_"

// MultiAuth returns a middleware that accepts both Clerk session JWTs (used by
// the Next.js web UI) and API keys (used by the CLI / GitHub Actions). The
// middleware is the single source of truth for the canonical SBOM upload
// endpoint POST /api/v1/projects/:id/sbom — see Trust Rescue 9.3.1 (#9). The
// existing Auth() and APIKeyAuth() middlewares are intentionally left
// untouched so any route that needs strictly one auth model keeps working.
//
// Decision rule:
//   - Authorization: Bearer sbh_... → API key path (apiKeyService.ValidateKey +
//     tenant context derived from the key's own tenant_id).
//   - Any other Bearer value → Clerk JWT path (delegates to Auth()).
//   - Self-hosted mode (no Clerk secret) with no Authorization header → falls
//     through to Auth()'s self-hosted handler, which provisions the default
//     tenant/user. This preserves the "self-host first" promise: a local
//     curl with no header still works against the local server.
//
// Failure modes:
//   - Bearer sbh_<key> that doesn't validate → 401 (does NOT fall through to
//     Clerk; an obviously-shaped API key that fails validation is a hard
//     denial so a leaked-and-revoked key cannot be retried as a JWT).
//   - Empty Authorization in SaaS mode → delegated to Auth(), which returns
//     401 with its usual error body.
func MultiAuth(
	cfg *config.Config,
	tenantRepo *repository.TenantRepository,
	userRepo *repository.UserRepository,
	apiKeyService *service.APIKeyService,
) echo.MiddlewareFunc {
	clerkAuth := Auth(cfg, tenantRepo, userRepo)

	return func(next echo.HandlerFunc) echo.HandlerFunc {
		clerkChain := clerkAuth(next)

		return func(c echo.Context) error {
			authHeader := c.Request().Header.Get("Authorization")
			token := strings.TrimPrefix(authHeader, BearerPrefix)

			// Detect API key by literal prefix. We only treat values with
			// `sbh_` as API keys — anything else (Clerk JWTs, empty, garbage)
			// goes through the Clerk/Self-hosted path.
			if token != authHeader && strings.HasPrefix(token, apiKeyPrefix) {
				return handleAPIKeyAuth(c, token, tenantRepo, userRepo, apiKeyService, next)
			}

			// Fall back to Clerk JWT (or self-hosted default) path.
			return clerkChain(c)
		}
	}
}

// handleAPIKeyAuth mirrors the APIKeyAuth + APIKeyTenant pair as a single
// inline step so MultiAuth can swap between auth strategies without re-entering
// Echo's middleware chain. Keep the order in sync with apikey.go (validate →
// set ContextKeyAPI → SetCurrentTenant → ContextKeyTenantID).
//
// M1 Codex review #F14: in addition to tenant + API-key context, the
// API-key path now also populates ContextKeyRole (mapped from
// api_keys.permissions) and ContextKeyUserID (a synthetic per-tenant
// user). Without these, handlers that gate on TenantContext.CanWrite()
// would reject every CLI sbh_... key with 403, and Decide / Reanalyse
// would reject every API-key call with "user identity required". The
// previous implementation worked for the SBOM upload / read-back routes
// only because those handlers did not consult CanWrite() or UserID; the
// triage / vex-drafts routes do, and the CLI's `sbomhub triage` command
// targets them with Bearer sbh_... auth.
func handleAPIKeyAuth(
	c echo.Context,
	rawKey string,
	tenantRepo *repository.TenantRepository,
	userRepo *repository.UserRepository,
	apiKeyService *service.APIKeyService,
	next echo.HandlerFunc,
) error {
	ctx := c.Request().Context()

	key, err := apiKeyService.ValidateKey(ctx, rawKey)
	if err != nil {
		slog.Debug("MultiAuth: API key validation failed", "error", err)
		return c.JSON(http.StatusUnauthorized, map[string]string{
			"error": err.Error(),
		})
	}
	c.Set(ContextKeyAPI, key)

	// API keys are tenant-scoped — every key carries a tenant_id by schema,
	// which is what enforces tenant isolation through Postgres RLS.
	if err := tenantRepo.SetCurrentTenant(ctx, key.TenantID); err != nil {
		slog.Error("MultiAuth: failed to set tenant context", "error", err)
		return c.JSON(http.StatusInternalServerError, map[string]string{
			"error": "failed to set tenant context",
		})
	}
	c.Set(ContextKeyTenantID, key.TenantID)

	// F14: map api_keys.permissions → ContextKeyRole so
	// TenantContext.CanWrite() / CanAdmin() behave correctly for the
	// API-key path. Triage / vex-drafts handlers gate on CanWrite() and
	// were previously unreachable for API-key clients because this
	// context value was never set (Role() defaulted to "" which fails
	// every allowlist check). The mapping defaults to RoleMember when
	// `permissions` is empty (matches APIKeyService's default of "write")
	// or unrecognised, so legacy keys created before this mapping keep
	// working with the documented write-capable default.
	c.Set(ContextKeyRole, roleFromAPIKeyPermissions(key.Permissions))

	// F14: resolve a synthetic per-tenant API-key user so
	// audit_logs.user_id (FK to users.id) and vex_drafts.decision_by
	// have a stable, non-NULL pointer to attribute API-key activity to.
	// One user is created per tenant on first use (idempotent lookup by
	// clerk_user_id = "api-key:<tenant_uuid>"), shared across all
	// subsequent API-key requests for that tenant. Operators can filter
	// audit_logs by name "API Key User" to isolate CLI/Actions traffic.
	apiUser, err := userRepo.GetOrCreateAPIKeyUser(ctx, key.TenantID)
	if err != nil {
		slog.Error("MultiAuth: failed to resolve API-key user", "error", err, "tenant_id", key.TenantID)
		return c.JSON(http.StatusInternalServerError, map[string]string{
			"error": "failed to resolve api-key user context",
		})
	}
	c.Set(ContextKeyUserID, apiUser.ID)
	c.Set(ContextKeyUser, apiUser)
	// ClerkUserID lets TenantContext.IsSelfHosted() distinguish API-key
	// requests from genuine self-hosted default-tenant requests. We do
	// not claim "self-hosted" here — the API key may have been issued in
	// SaaS mode — but we do leave a recognisable marker so future
	// debugging (and the Codex round 7+ reviewer) can tell the two
	// pathways apart in logs.
	c.Set(ContextKeyClerkUserID, "api-key:"+key.TenantID.String())

	return next(c)
}

// roleFromAPIKeyPermissions maps the api_keys.permissions string to the
// TenantContext role allowlist (model.RoleViewer / RoleMember / RoleAdmin /
// RoleOwner).
//
// Recognised values (case-insensitive, trimmed):
//   - "read"          → RoleViewer (no CanWrite, no CanAdmin)
//   - "write"         → RoleMember (CanWrite, no CanAdmin)
//   - "admin"/"owner" → RoleAdmin  (CanWrite, CanAdmin)
//
// Default (empty string OR any unrecognised value) → RoleViewer.
//
// M1 Codex review #F17 fix: the previous default was RoleMember, which
// meant a stored permission of "readonly", "none", or simply a typo got
// silently promoted to write-capable on every MultiAuth-fronted endpoint.
// That is a fail-open default in a security product. The fix flips the
// default to RoleViewer (fail-closed) so any value the service-side
// validation in apikey.go::CreateKey did not bless — including direct DB
// INSERTs and rows persisted before that validation was in place — is
// treated as the lowest-privilege role.
//
// Companion validation lives in IsKnownAPIKeyPermission below; callers
// that need to reject unknown values at creation time (rather than
// silently downgrade them at validation time) use that helper. The two
// together implement the fail-closed contract end-to-end: at creation
// the service refuses unknown values with 400; at validation the
// middleware refuses to grant them write power even if they slipped in
// through some other path.
func roleFromAPIKeyPermissions(perm string) string {
	switch strings.ToLower(strings.TrimSpace(perm)) {
	case "read":
		return model.RoleViewer
	case "admin", "owner":
		return model.RoleAdmin
	case "write":
		return model.RoleMember
	default:
		// F17: fail-closed. An empty string here normally only reaches
		// this branch via direct DB injection — APIKeyService.CreateKey
		// fills in "write" when the request omits permissions. Mapping
		// the unknown branch to RoleViewer rather than RoleMember means
		// that even if a row somehow ends up empty / typo'd, it cannot
		// be used to drive write endpoints.
		return model.RoleViewer
	}
}

// IsKnownAPIKeyPermission is re-exported here for callers that already
// import the middleware package; the canonical definition lives in
// model.IsKnownAPIKeyPermission. The helper had to move to the model
// package to break the middleware ↔ service import cycle introduced
// when APIKeyService.CreateKey started validating permissions through
// it (M1 Codex review #F17). See model/apikey.go for the rationale.
func IsKnownAPIKeyPermission(perm string) bool {
	return model.IsKnownAPIKeyPermission(perm)
}
