package service

import (
	"bytes"
	"context"
	"encoding/csv"
	"errors"
	"strings"
	"testing"

	"github.com/google/uuid"
	"github.com/sbomhub/sbomhub/internal/model"
	"github.com/xuri/excelize/v2"
)

// ----------------------------------------------------------------------------
// M46 Track C regression — GenerateComplianceExcel used to discard the error
// return of ~50 excelize calls (errcheck findings), so a failed cell write
// still produced a "successful" but corrupt/incomplete workbook. These tests
// pin (a) the error-collection mechanism the generator now routes every
// write through, exercised with REAL excelize errors, and (b) the happy-path
// workbook/CSV content so the errcheck refactor cannot silently change the
// report layout.
// ----------------------------------------------------------------------------

func testComplianceResult() *model.ComplianceResult {
	failDetail := "SBOMがアップロードされていません"
	return &model.ComplianceResult{
		ProjectID: uuid.New(),
		Score:     1,
		MaxScore:  2,
		Categories: []model.ComplianceCategory{
			{
				Name:     string(model.ComplianceCategorySBOM),
				Label:    "SBOM生成",
				Score:    1,
				MaxScore: 2,
				Checks: []model.ComplianceCheck{
					{ID: "required_fields", Label: "必須フィールドが含まれている", Passed: true},
					{ID: "sbom_exists", Label: "SBOMが登録されている", Passed: false, Details: &failDetail},
				},
			},
		},
	}
}

func TestReportErrs_KeepsFirstRealExcelizeError(t *testing.T) {
	f := excelize.NewFile()
	defer func() {
		if err := f.Close(); err != nil {
			t.Errorf("close workbook: %v", err)
		}
	}()

	ec := &reportErrs{}
	ec.collect(nil)
	if ec.err != nil {
		t.Fatalf("collect(nil) must not record an error, got %v", ec.err)
	}

	// Real excelize failure of the exact call shape GenerateComplianceExcel
	// uses: writing to a sheet that does not exist.
	ec.collect(f.SetCellValue("no-such-sheet", "A1", "x"))
	if ec.err == nil {
		t.Fatal("expected SetCellValue on missing sheet to be collected")
	}
	first := ec.err

	// A later, different failure must not overwrite the first one.
	ec.collect(errors.New("second error"))
	if !errors.Is(ec.err, first) {
		t.Fatalf("first error was overwritten: got %v, want %v", ec.err, first)
	}
	ec.collect(nil)
	if !errors.Is(ec.err, first) {
		t.Fatalf("collect(nil) cleared the recorded error: got %v", ec.err)
	}
}

func TestGenerateComplianceExcel_SuccessProducesReadableWorkbook(t *testing.T) {
	s := &ComplianceService{}
	result := testComplianceResult()

	b, err := s.GenerateComplianceExcel(context.Background(), result.ProjectID, result)
	if err != nil {
		t.Fatalf("GenerateComplianceExcel: %v", err)
	}

	f, err := excelize.OpenReader(bytes.NewReader(b))
	if err != nil {
		t.Fatalf("generated bytes are not a readable workbook: %v", err)
	}
	defer func() {
		if err := f.Close(); err != nil {
			t.Errorf("close workbook: %v", err)
		}
	}()

	wantSheets := []string{"サマリー", "チェック項目詳細", "推奨事項"}
	got := f.GetSheetList()
	for _, want := range wantSheets {
		found := false
		for _, name := range got {
			if name == want {
				found = true
				break
			}
		}
		if !found {
			t.Fatalf("sheet %q missing; sheets = %v", want, got)
		}
	}

	title, err := f.GetCellValue("サマリー", "A1")
	if err != nil || title != "経産省SBOMガイドライン コンプライアンスレポート" {
		t.Fatalf("summary title = %q err = %v", title, err)
	}
	score, err := f.GetCellValue("サマリー", "B6")
	if err != nil || score != "1 / 2 (50%)" {
		t.Fatalf("total score cell = %q err = %v, want \"1 / 2 (50%%)\"", score, err)
	}

	// Detail rows: row 2 = passed check, row 3 = failed check with details
	// and a recommendation.
	if v, _ := f.GetCellValue("チェック項目詳細", "C2"); v != "達成" {
		t.Fatalf("detail C2 = %q, want 達成", v)
	}
	if v, _ := f.GetCellValue("チェック項目詳細", "C3"); v != "未達成" {
		t.Fatalf("detail C3 = %q, want 未達成", v)
	}
	if v, _ := f.GetCellValue("チェック項目詳細", "D3"); v != "SBOMがアップロードされていません" {
		t.Fatalf("detail D3 = %q", v)
	}
	if v, _ := f.GetCellValue("推奨事項", "A2"); v != "SBOMが登録されている" {
		t.Fatalf("recommendation A2 = %q", v)
	}
}

func TestGenerateComplianceCSV_SuccessAndContent(t *testing.T) {
	s := &ComplianceService{}
	result := testComplianceResult()

	b, err := s.GenerateComplianceCSV(context.Background(), result.ProjectID, result)
	if err != nil {
		t.Fatalf("GenerateComplianceCSV: %v", err)
	}
	if !bytes.HasPrefix(b, []byte{0xEF, 0xBB, 0xBF}) {
		t.Fatal("CSV must start with a UTF-8 BOM for Excel compatibility")
	}

	r := csv.NewReader(strings.NewReader(string(bytes.TrimPrefix(b, []byte{0xEF, 0xBB, 0xBF}))))
	r.FieldsPerRecord = -1
	records, err := r.ReadAll()
	if err != nil {
		t.Fatalf("generated CSV is not parseable: %v", err)
	}
	// 4 metadata rows + column header + 2 data rows (the separator row is
	// an empty line, which csv.Reader skips)
	if len(records) != 7 {
		t.Fatalf("record count = %d, want 7; records = %v", len(records), records)
	}
	if records[0][0] != "経済産業省コンプライアンスレポート" {
		t.Fatalf("header = %v", records[0])
	}
	failedRow := records[6]
	if failedRow[1] != "SBOMが登録されている" || failedRow[2] != "未達成" ||
		failedRow[3] != "SBOMがアップロードされていません" || failedRow[4] == "" {
		t.Fatalf("failed-check row = %v", failedRow)
	}
}
