package service

// M49 — the executive report's summary lines are evidence handed to an
// auditor. "Average MTTR 0.0 hours" and "SLO achievement 100.0%" must never
// stand in for "no vulnerability was resolved in this period": for these two
// metrics 0 and 100 are the BEST possible values, so the sentinel does not
// merely lose information, it manufactures a favourable finding.

import (
	"bytes"
	"testing"

	"github.com/xuri/excelize/v2"

	"github.com/sbomhub/sbomhub/internal/model"
)

func TestReportMTTRText_NilIsNotMeasuredLabel(t *testing.T) {
	ja := GetTranslations("ja")
	en := GetTranslations("en")

	if got := reportMTTRText(nil, ja); got != "未計測" {
		t.Errorf("reportMTTRText(nil, ja) = %q, want 未計測", got)
	}
	if got := reportMTTRText(nil, en); got != "Not measured" {
		t.Errorf("reportMTTRText(nil, en) = %q, want \"Not measured\"", got)
	}
	// A genuinely measured value — including a real sub-rounding 0.0, which a
	// fast-moving team can produce — stays numeric and distinguishable.
	if got := reportMTTRText(f64p(0), en); got != "0.0 hours" {
		t.Errorf("reportMTTRText(0.0, en) = %q, want \"0.0 hours\" (a real measurement)", got)
	}
	if got := reportMTTRText(f64p(12.5), en); got != "12.5 hours" {
		t.Errorf("reportMTTRText(12.5, en) = %q, want \"12.5 hours\"", got)
	}
	if got := reportMTTRValue(nil, en); got != "Not measured" {
		t.Errorf("reportMTTRValue(nil, en) = %q, want \"Not measured\"", got)
	}
	if got := reportMTTRValue(f64p(12.5), en); got != "12.5" {
		t.Errorf("reportMTTRValue(12.5, en) = %q, want \"12.5\"", got)
	}
}

func TestReportPercentText_NilIsNotMeasuredLabel(t *testing.T) {
	ja := GetTranslations("ja")
	en := GetTranslations("en")

	if got := reportPercentText(nil, ja); got != "未計測" {
		t.Errorf("reportPercentText(nil, ja) = %q, want 未計測", got)
	}
	if got := reportPercentText(nil, en); got != "Not measured" {
		t.Errorf("reportPercentText(nil, en) = %q, want \"Not measured\"", got)
	}
	// A measured 0% is a real (bad) finding and must NOT read as unmeasured.
	if got := reportPercentText(f64p(0), en); got != "0.0%" {
		t.Errorf("reportPercentText(0.0, en) = %q, want \"0.0%%\" (a real miss, not absence of data)", got)
	}
	if got := reportPercentText(f64p(99.5), en); got != "99.5%" {
		t.Errorf("reportPercentText(99.5, en) = %q, want \"99.5%%\"", got)
	}
	if got := reportPercentValue(nil, en); got != "Not measured" {
		t.Errorf("reportPercentValue(nil, en) = %q, want \"Not measured\"", got)
	}
	if got := reportPercentValue(f64p(99.5), en); got != "99.5" {
		t.Errorf("reportPercentValue(99.5, en) = %q, want \"99.5\"", got)
	}
}

// excelSummaryCells reads the two M49 summary cells out of a generated
// workbook. The summary block starts at row 5 in the order
// Projects / Components / TotalVulnerabilities / ResolvedInPeriod /
// AverageMTTR / SLOAchievement / ComplianceScore.
func excelSummaryCells(t *testing.T, data *model.ExecutiveReportData) (mttr, slo string) {
	t.Helper()
	svc := NewReportService(nil, nil, nil, nil, nil, nil, t.TempDir())
	tr := GetTranslations("ja")

	b, err := svc.generateExcel(data, model.ReportTypeExecutive, "ja")
	if err != nil {
		t.Fatalf("generateExcel: %v", err)
	}
	f, err := excelize.OpenReader(bytes.NewReader(b))
	if err != nil {
		t.Fatalf("generated bytes are not a readable workbook: %v", err)
	}
	defer func() {
		if err := f.Close(); err != nil {
			t.Errorf("close workbook: %v", err)
		}
	}()

	mttr, _ = f.GetCellValue(tr.SheetSummary, "B9")
	slo, _ = f.GetCellValue(tr.SheetSummary, "B10")
	return mttr, slo
}

func TestGenerateExcel_UnmeasuredMTTRAndSLOCellsAreLabelsNotNumbers(t *testing.T) {
	tr := GetTranslations("ja")

	// Measured baseline (fixture values) — anchors the cell positions so the
	// unmeasured assertion below cannot pass by reading the wrong cells.
	mttr, slo := excelSummaryCells(t, buildFullReportData())
	if mttr != "12.5" {
		t.Fatalf("measured MTTR cell B9 = %q, want 12.5 (cell mapping drifted?)", mttr)
	}
	if slo != "99.5" {
		t.Fatalf("measured SLO cell B10 = %q, want 99.5 (cell mapping drifted?)", slo)
	}

	data := buildFullReportData()
	data.Summary.AverageMTTRHours = nil
	data.Summary.SLOAchievementPct = nil

	mttr, slo = excelSummaryCells(t, data)
	if mttr != tr.NotMeasured {
		t.Errorf("unmeasured MTTR cell B9 = %q, want %q — an auditor must not read 0.0 hours "+
			"as evidence of instant remediation", mttr, tr.NotMeasured)
	}
	if slo != tr.NotMeasured {
		t.Errorf("unmeasured SLO cell B10 = %q, want %q — an auditor must not read 100%% as "+
			"evidence of compliance nobody measured", slo, tr.NotMeasured)
	}
}

// TestGeneratePDF_UnmeasuredSummaryDoesNotPanic keeps the PDF arm honest:
// the same nil summary must render (through reportMTTRText /
// reportPercentText) instead of dereferencing a nil pointer.
func TestGeneratePDF_UnmeasuredSummaryRenders(t *testing.T) {
	svc := NewReportService(nil, nil, nil, nil, nil, nil, t.TempDir())

	data := buildFullReportData()
	data.Summary.AverageMTTRHours = nil
	data.Summary.SLOAchievementPct = nil

	for _, reportType := range []string{model.ReportTypeExecutive, model.ReportTypeTechnical} {
		b, err := svc.generatePDF(data, reportType, "ja")
		if err != nil {
			t.Fatalf("generatePDF(%s) with an unmeasured summary: %v", reportType, err)
		}
		if len(b) == 0 {
			t.Errorf("generatePDF(%s) returned 0 bytes", reportType)
		}
	}
}

func TestReportComplianceScoreText_ZeroMaxIsNotMeasured(t *testing.T) {
	ja := GetTranslations("ja")
	en := GetTranslations("en")

	// No checklist configured: "0 / 0" is the absence of an assessment, not a
	// score of zero (M49, Codex round 4).
	if got := reportComplianceScoreText(0, 0, ja); got != "未計測" {
		t.Errorf("reportComplianceScoreText(0, 0, ja) = %q, want 未計測", got)
	}
	if got := reportComplianceScoreText(0, 0, en); got != "Not measured" {
		t.Errorf("reportComplianceScoreText(0, 0, en) = %q, want \"Not measured\"", got)
	}
	// A REAL 0 out of a configured scorecard is a finding and must stay numeric.
	if got := reportComplianceScoreText(0, 16, en); got != "0 / 16" {
		t.Errorf("reportComplianceScoreText(0, 16, en) = %q, want \"0 / 16\"", got)
	}
	if got := reportComplianceScoreText(8, 16, en); got != "8 / 16" {
		t.Errorf("reportComplianceScoreText(8, 16, en) = %q, want \"8 / 16\"", got)
	}
}

func TestGenerateExcel_UnassessedComplianceCellIsLabelNotZeroOverZero(t *testing.T) {
	tr := GetTranslations("ja")

	data := buildFullReportData()
	data.Summary.ComplianceScore = 0
	data.Summary.ComplianceMaxScore = 0

	svc := NewReportService(nil, nil, nil, nil, nil, nil, t.TempDir())
	b, err := svc.generateExcel(data, model.ReportTypeExecutive, "ja")
	if err != nil {
		t.Fatalf("generateExcel: %v", err)
	}
	f, err := excelize.OpenReader(bytes.NewReader(b))
	if err != nil {
		t.Fatalf("generated bytes are not a readable workbook: %v", err)
	}
	defer func() {
		if err := f.Close(); err != nil {
			t.Errorf("close workbook: %v", err)
		}
	}()

	// Summary block row 11 = compliance score (see excelSummaryCells).
	if v, _ := f.GetCellValue(tr.SheetSummary, "B11"); v != tr.NotMeasured {
		t.Errorf("unassessed compliance cell B11 = %q, want %q (never \"0 / 0\")", v, tr.NotMeasured)
	}
}
