package service

// M46 Track A wave 4 — the report renderers share the Top Risks rows with the
// dashboard (Codex round B-1 Medium 1): an un-scored CVE (nil CVSSScore) must
// render as the locale's Unscored label in the PDF body and the Excel Top
// Risks sheet, never as "CVSS 0.0" (CVSS 0.0 is a real "None" score).

import (
	"bytes"
	"testing"

	"github.com/xuri/excelize/v2"

	"github.com/sbomhub/sbomhub/internal/model"
)

func TestReportCVSSText_NilIsUnscoredLabel(t *testing.T) {
	ja := GetTranslations("ja")
	en := GetTranslations("en")

	if got := reportCVSSText(nil, ja); got != "未採点" {
		t.Errorf("reportCVSSText(nil, ja) = %q, want 未採点", got)
	}
	if got := reportCVSSText(nil, en); got != "Unscored" {
		t.Errorf("reportCVSSText(nil, en) = %q, want Unscored", got)
	}
	// Real scores — including the genuine 0.0 "None" — stay numeric.
	if got := reportCVSSText(f64p(0), ja); got != "0.0" {
		t.Errorf("reportCVSSText(0.0, ja) = %q, want \"0.0\" (real 'None' score)", got)
	}
	if got := reportCVSSText(f64p(9.1), en); got != "9.1" {
		t.Errorf("reportCVSSText(9.1, en) = %q, want \"9.1\"", got)
	}
}

func TestGenerateExcel_UnscoredCVSSCellIsLabelNotZero(t *testing.T) {
	svc := NewReportService(nil, nil, nil, nil, nil, nil, t.TempDir())
	tr := GetTranslations("ja")

	data := buildFullReportData()
	// Row 2: scored 9.1 (fixture). Row 3: un-scored CRITICAL. Row 4: real 0.0.
	data.TopRisks = append(data.TopRisks,
		model.TopRisk{CVEID: "CVE-2026-0002", EPSSScore: f64p(0.5), CVSSScore: nil,
			Severity: "CRITICAL", ProjectName: "app-b", ComponentName: "libq"},
		model.TopRisk{CVEID: "CVE-2026-0003", EPSSScore: f64p(0.1), CVSSScore: f64p(0),
			Severity: "LOW", ProjectName: "app-c", ComponentName: "libr"},
	)

	b, err := svc.generateExcel(data, model.ReportTypeExecutive, "ja")
	if err != nil {
		t.Fatalf("generateExcel: %v", err)
	}
	f, err := excelize.OpenReader(bytes.NewReader(b))
	if err != nil {
		t.Fatalf("generated bytes are not a readable workbook: %v", err)
	}
	defer func() {
		if err := f.Close(); err != nil {
			t.Errorf("close workbook: %v", err)
		}
	}()

	if v, _ := f.GetCellValue(tr.SheetTopRisks, "D2"); v != "9.1" {
		t.Errorf("scored CVSS D2 = %q, want 9.1", v)
	}
	// The un-scored row must carry the label, not a numeric 0.
	if v, _ := f.GetCellValue(tr.SheetTopRisks, "D3"); v != tr.Unscored {
		t.Errorf("un-scored CVSS D3 = %q, want %q (never 0.0)", v, tr.Unscored)
	}
	// The REAL 0.0 ("None") score stays numeric — distinguishable from
	// un-scored.
	if v, _ := f.GetCellValue(tr.SheetTopRisks, "D4"); v != "0" {
		t.Errorf("real 0.0-scored CVSS D4 = %q, want 0", v)
	}
}
