package nullscan

import (
	"context"
	"database/sql"
	_ "embed"
	"encoding/json"
	"fmt"
	"sort"
)

// Column is one column's nullability snapshot as seen by PostgreSQL
// (pg_attribute.attnotnull) plus its formatted type for human review.
type Column struct {
	Nullable bool   `json:"nullable"`
	Type     string `json:"type"`
}

// Schema is the nullability snapshot of the live database, generated by
// `cmd/nullscan -dump-schema` and committed as schema.json so the analyzer
// runs hermetically (no DB) in CI.
//
// Views (and materialized views) are recorded separately: their column
// nullability is NOT trustworthy (pg_attribute reports attnotnull=false for
// almost everything), so the analyzer deliberately treats any query touching
// a view as UNANALYZABLE instead of guessing.
type Schema struct {
	// GeneratedBy documents the regeneration command for humans reading
	// the JSON; it is not consumed programmatically.
	GeneratedBy string `json:"generated_by"`
	// Tables maps table name -> column name -> column info. Ordinary
	// (relkind 'r') and partitioned (relkind 'p') tables.
	Tables map[string]map[string]Column `json:"tables"`
	// Views maps view name -> column name -> column info for relkind 'v'
	// and 'm'. Present for inventory only; see the type comment.
	Views map[string]map[string]Column `json:"views"`
}

//go:embed schema.json
var embeddedSchemaJSON []byte

// LoadEmbeddedSchema parses the schema.json snapshot compiled into the
// binary. This is what `cmd/nullscan` (without -dump-schema) uses, so CI
// needs no database.
func LoadEmbeddedSchema() (*Schema, error) {
	var s Schema
	if err := json.Unmarshal(embeddedSchemaJSON, &s); err != nil {
		return nil, fmt.Errorf("parse embedded schema.json: %w", err)
	}
	if len(s.Tables) == 0 {
		return nil, fmt.Errorf("embedded schema.json has no tables; regenerate with: go run ./cmd/nullscan -dump-schema")
	}
	return &s, nil
}

// DumpSchema reads table/view column nullability from the connected
// PostgreSQL via pg_attribute. Only the public schema is considered (the
// application owns exactly that schema).
func DumpSchema(ctx context.Context, db *sql.DB) (*Schema, error) {
	const q = `
		SELECT c.relname,
		       a.attname,
		       NOT a.attnotnull AS nullable,
		       format_type(a.atttypid, a.atttypmod) AS coltype,
		       c.relkind::text
		FROM pg_attribute a
		JOIN pg_class c ON c.oid = a.attrelid
		JOIN pg_namespace n ON n.oid = c.relnamespace
		WHERE n.nspname = 'public'
		  AND c.relkind IN ('r', 'p', 'v', 'm')
		  AND a.attnum > 0
		  AND NOT a.attisdropped
		ORDER BY c.relname, a.attnum`

	rows, err := db.QueryContext(ctx, q)
	if err != nil {
		return nil, fmt.Errorf("query pg_attribute: %w", err)
	}
	defer rows.Close()

	s := &Schema{
		GeneratedBy: "go run ./cmd/nullscan -dump-schema (reads MIGRATE_DATABASE_URL or DATABASE_URL)",
		Tables:      map[string]map[string]Column{},
		Views:       map[string]map[string]Column{},
	}
	for rows.Next() {
		var rel, col, typ, kind string
		var nullable bool
		if err := rows.Scan(&rel, &col, &nullable, &typ, &kind); err != nil {
			return nil, fmt.Errorf("scan pg_attribute row: %w", err)
		}
		dst := s.Tables
		if kind == "v" || kind == "m" {
			dst = s.Views
		}
		if dst[rel] == nil {
			dst[rel] = map[string]Column{}
		}
		dst[rel][col] = Column{Nullable: nullable, Type: typ}
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate pg_attribute rows: %w", err)
	}
	if len(s.Tables) == 0 {
		return nil, fmt.Errorf("no tables found in schema 'public' — wrong database?")
	}
	return s, nil
}

// MarshalDeterministic renders the schema as stable, diff-friendly JSON:
// two-space indent, map keys sorted (encoding/json sorts string map keys),
// trailing newline. Byte-identical output for identical schemas is the
// contract the drift-guard integration test relies on.
func (s *Schema) MarshalDeterministic() ([]byte, error) {
	b, err := json.MarshalIndent(s, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(b, '\n'), nil
}

// TableNames returns the sorted table names (test/debug helper).
func (s *Schema) TableNames() []string {
	names := make([]string, 0, len(s.Tables))
	for n := range s.Tables {
		names = append(names, n)
	}
	sort.Strings(names)
	return names
}
